CREATE TABLE Agenda (
IdContacto INT IDENTITY (1,1) PRIMARY KEY, -- ID PRIMARIO 
Nombre NVARCHAR(100) NOT NULL, --NOMBRE DE LA PERSONA
Apellido NVARCHAR(100) NOT NULL,-- APELLIDO DE LA PERSONA 
Telefono NVARCHAR(15) NOT NULL,-- TELEFONO DE LA PERSONA
Email NVARCHAR(150) UNIQUE NOT NULL -- EMAIL DE LA PERSONA

);